language: ruby
rvm:
- 2.3.3

deploy:
  provider: heroku
  app: people-pipeline
  api_key:
    secure: u0a3qntwfIoYg2qw4Icy6ca48hGuOm+fNh165e1lDPuyxZYO5qM7XGWR9jzSWSz0Im8BfaKnB0oY8S4oTiiFcBoDMMdgSuPe3JsPrn36mCddDoqXjzxG5RJxTmsAAMVhI34SbCNPAbzEz2LxL03Vy8a4mSwdI3XRnMFhv/5NdzUEOjAOgmcXDfuGjexIUz3v9FpugSIGky3sN65yOu9pWzM3ir2KBhseC0i16kP7ETQ+7Bi+I3iDWTVLB+FCQAfKsQsJF7frncAralkhBt9VTFBU+cTMoxMIRPAPsd4I/Nmb7LN/6y2wiNU55K+IJxxHh9T0GY4/NJ6uVrN/j0OYgiCGgySRxvBpVDjUaPBnGKdaUl7G5vx3PE8+tEVZrLlLXMI+E/OZI7DQKFMJgoPgBIAYvcNvYPm/42QPmowtWHuiYfY89dVCElg9fzU/jr+zvJfX8gviafYkOgXvv/iFgxuSNPJSa/S7gvOd+pT7vJHRL/WsWQ8pJuwmphaTzlbGMLlrpoGtqghmiCwI0oD/jPllQ2vDaGUIPnPdxAeftZKUkiz1movpEFWURD7v2TdLiokWKN8JBK7630y3Vhh4GTPUXLKQnTaenrRl67Ca4FbkkPo7ara78LaRE/zJFuEEmGwqd+fgsYxzSF7SPQ1Jv7IvNSHhCqHCmhxb4WhUp7Y=
